### ISSUE TITLE
speedometer issue

### ISSUE THREAD

**Issue by csizi94** [joe-rogan-0001/joehud#13]
We have some problem with the speedometer it doesn't shows up, any idea how can we solve it?
![Screenshot 2021-11-30 043941](https://user-images.githubusercontent.com/95265726/143981925-b6028a63-bb99-4125-bafa-289fb8938789.png)

**Comment by cowardtv** [comment]
happened to me also

**Comment by cowardtv** [comment]
fixed it by removing speedfps

**Comment by soibois** [comment]
what did you remove exactly? @cowardtv

**Comment by cowardtv** [comment]
go to the client file search for the speedfps line 73 and just remove the speedfps and put like 100 wait time

**Comment by soibois** [comment]
what should the code look like in its place so i can copy pasta pls <3 @cowardtv

**Comment by joe-rogan-0001** [comment]
I've added a temporary fix, you can download this in the releases.
