### ISSUE TITLE
Minimap and js errors

### ISSUE THREAD

**Issue by FBFezz** [joe-rogan-0001/joehud#3]
Using the latest version this happens,

![image](https://user-images.githubusercontent.com/43589668/135361658-35e14658-0bdb-47f6-89a9-0b56d6ad2631.png)

![image](https://user-images.githubusercontent.com/43589668/135361762-0b9a7b4c-544e-4146-87a6-720bcdc5e7b1.png)

**Comment by FBFezz** [comment]
For some reason the map shows when going 72 mph or above

**Comment by joe-rogan-0001** [comment]
Fixed.
